package br.org.catolicasc.vendas.model;

public enum StatusPedido {

    PAGAMENTO_PENDENTE,
    PAGAMENTO_APROVADO,
    CARENCIA_PARA_CANCELAMENTO,
    PRONTO_MANUSEIO,
    INICIAR_MANUSEIO,
    PREPARANDO_ENTREGA,
    CANCELAMENTO_SOLICITADO,
    VERIFICANDO_ENVIO,
    FATURADO,
    CANCELAR,
    CANCELADO,
    ENVIADO

}
